### ISSUE TITLE
Print function does not render as the recipe does

### ISSUE THREAD

**Issue by gabimoncha** [jsreport/jsreport-browser-client#4]
I prepared a template for a report and I am using `html-with-browser-client` recipe.
With `chrome-pdf` it renders ok, so I chose this recipe for the template. But when I download the report it renders only the text and no css.
Here is my example in the playground:
https://playground.jsreport.net/w/gabrielmoncea/ZOmcJy5A

**Comment by bjrmatos** [comment]
hi! checking your example i see that you are using the following to render the template

```js
jsreport.download("report.pdf", {
        template: {
          content: document.documentElement.outerHTML,
          engine: "handlebars",
          recipe: "chrome-pdf",
          chrome: {
              printBackground: true
          }
        }
      });
```
the problem with this code is that you are not passing the full content of the page, or in other words you are ignoring the css part that it is in the `head` tag of the page, `document.getElementById("frame").outerHTML` does not contain the full html as you may think.. i see two solutions for this:

- use `document.documentElement.outerHTML` instead of `document.getElementById("frame").outerHTML` to get the full content

- instead of passing `template.content`, just pass `template.name` 

```js
jsreport.download("report.pdf", {
        template: {
          name: 'Invoice',
          engine: "handlebars",
          recipe: "chrome-pdf",
          chrome: {
              printBackground: true
          }
        }
      })
```

hope it helps you

**Comment by gabimoncha** [comment]
Yes it does. I look it up in the examples and figured it out 👍
